source 'https://rubygems.org'


gem 'coffee-rails'
gem 'ember-rails'
gem 'ember-source'
gem 'emblem-rails'
gem 'faker'
gem 'haml-rails'
gem 'jbuilder'
gem 'jquery-rails'
gem 'rails_12factor'
gem 'sqlite3'
gem 'puma'
gem 'rails' 
gem 'sass-rails'
gem 'uglifier'
gem 'pry-rails'
